from django.core.management.base import BaseCommand
from django.db import transaction

from processes.models import ProcessType

CATALOG = [
    {
        "code": "OSPOSOBLJAVANJE_BZR",
        "name": "Osposobljavanje zaposlenih za bezbedan rad",
        "subject_kind": ProcessType.SUBJECT_EMPLOYEE,
        "domain": ProcessType.DOMAIN_BZNR,
        "shape": ProcessType.SHAPE_PERIODIC,
        "proof_kind": ProcessType.PROOF_RECORDED,
        "legal_basis": "Zakon o BZR 35/2023, čl. 33-34",
        "default_period_months": 36,
        "period_rules": [{"when": {"risk": "high"}, "months": 12}],
        "reminder_offsets": [-30, 0, 14],
        "applicability_rule": {"always": True},
        "company_document_kind": "",
        "include_in_medical_exam_record": False,
    },
    {
        "code": "LEKARSKI_PREGLED",
        "name": "Periodični lekarski pregled",
        "subject_kind": ProcessType.SUBJECT_EMPLOYEE,
        "domain": ProcessType.DOMAIN_BZNR,
        "shape": ProcessType.SHAPE_PERIODIC,
        "proof_kind": ProcessType.PROOF_UPLOAD,
        "legal_basis": "Zakon o BZR 35/2023, čl. 56",
        "default_period_months": None,
        "period_rules": [{"when": {"risk": "high"}, "months": 12}],
        "reminder_offsets": [-30, -7, 0, 14],
        "applicability_rule": {"high_risk_only": True},
        "company_document_kind": "",
        "include_in_medical_exam_record": True,
    },
    {
        "code": "AKT_PROCENA_RIZIKA",
        "name": "Akt o proceni rizika",
        "subject_kind": ProcessType.SUBJECT_CLIENT_COMPANY,
        "domain": ProcessType.DOMAIN_BZNR,
        "shape": ProcessType.SHAPE_LIVING_DOCUMENT,
        "proof_kind": ProcessType.PROOF_GENERATED,
        "legal_basis": "Zakon o BZR 35/2023, čl. 16",
        "default_period_months": None,
        "period_rules": [],
        "reminder_offsets": [],
        "applicability_rule": {"always": True},
        "company_document_kind": "",
        "include_in_medical_exam_record": False,
    },
    {
        "code": "PRAVILNIK_BZNR",
        "name": "Pravilnik o bezbednosti i zdravlju na radu",
        "subject_kind": ProcessType.SUBJECT_CLIENT_COMPANY,
        "domain": ProcessType.DOMAIN_BZNR,
        "shape": ProcessType.SHAPE_LIVING_DOCUMENT,
        "proof_kind": ProcessType.PROOF_GENERATED,
        "legal_basis": "",
        "default_period_months": None,
        "period_rules": [],
        "reminder_offsets": [],
        "applicability_rule": {"always": True},
        "company_document_kind": "RULEBOOK_OSH",
        "include_in_medical_exam_record": False,
    },
    {
        "code": "PROGRAM_OBUKE_ZAPOSLENI",
        "name": "Program obuke za zaposlene",
        "subject_kind": ProcessType.SUBJECT_CLIENT_COMPANY,
        "domain": ProcessType.DOMAIN_BZNR,
        "shape": ProcessType.SHAPE_LIVING_DOCUMENT,
        "proof_kind": ProcessType.PROOF_GENERATED,
        "legal_basis": "",
        "default_period_months": None,
        "period_rules": [],
        "reminder_offsets": [],
        "applicability_rule": {"always": True},
        "company_document_kind": "TRAINING_EMPLOYEES",
        "include_in_medical_exam_record": False,
    },
    {
        "code": "PROGRAM_OBUKE_RUKOVODIOCI",
        "name": "Program obuke za rukovodioce",
        "subject_kind": ProcessType.SUBJECT_CLIENT_COMPANY,
        "domain": ProcessType.DOMAIN_BZNR,
        "shape": ProcessType.SHAPE_LIVING_DOCUMENT,
        "proof_kind": ProcessType.PROOF_GENERATED,
        "legal_basis": "",
        "default_period_months": None,
        "period_rules": [],
        "reminder_offsets": [],
        "applicability_rule": {"always": True},
        "company_document_kind": "TRAINING_MANAGERS",
        "include_in_medical_exam_record": False,
    },
    {
        "code": "PRAVILNIK_LZO",
        "name": "Pravilnik o ličnoj zaštitnoj opremi",
        "subject_kind": ProcessType.SUBJECT_CLIENT_COMPANY,
        "domain": ProcessType.DOMAIN_BZNR,
        "shape": ProcessType.SHAPE_LIVING_DOCUMENT,
        "proof_kind": ProcessType.PROOF_GENERATED,
        "legal_basis": "",
        "default_period_months": None,
        "period_rules": [],
        "reminder_offsets": [],
        "applicability_rule": {"always": True},
        "company_document_kind": "RULEBOOK_PPE",
        "include_in_medical_exam_record": False,
    },
    {
        "code": "PROGRAM_OBUKE_LZO",
        "name": "Program obuke za ličnu zaštitnu opremu",
        "subject_kind": ProcessType.SUBJECT_CLIENT_COMPANY,
        "domain": ProcessType.DOMAIN_BZNR,
        "shape": ProcessType.SHAPE_LIVING_DOCUMENT,
        "proof_kind": ProcessType.PROOF_GENERATED,
        "legal_basis": "",
        "default_period_months": None,
        "period_rules": [],
        "reminder_offsets": [],
        "applicability_rule": {"always": True},
        "company_document_kind": "TRAINING_PPE",
        "include_in_medical_exam_record": False,
    },
    {
        "code": "UGOVOR",
        "name": "Ugovor o pružanju usluga BZNR",
        "subject_kind": ProcessType.SUBJECT_CLIENT_COMPANY,
        "domain": ProcessType.DOMAIN_BZNR,
        "shape": ProcessType.SHAPE_APPOINTMENT,
        "proof_kind": ProcessType.PROOF_UPLOAD,
        "legal_basis": "",
        "default_period_months": None,
        "period_rules": [],
        "reminder_offsets": [],
        "applicability_rule": {"always": True},
        "company_document_kind": "CONTRACT",
        "include_in_medical_exam_record": False,
    },
    {
        "code": "ODLUKA_SAVETNIK_HEMIKALIJE",
        "name": "Odluka o imenovanju savetnika za hemikalije",
        "subject_kind": ProcessType.SUBJECT_CLIENT_COMPANY,
        "domain": ProcessType.DOMAIN_BZNR,
        "shape": ProcessType.SHAPE_APPOINTMENT,
        "proof_kind": ProcessType.PROOF_UPLOAD,
        "legal_basis": "",
        "default_period_months": None,
        "period_rules": [],
        "reminder_offsets": [],
        "applicability_rule": {"always": True},
        "company_document_kind": "DECISION",
        "include_in_medical_exam_record": False,
    },
    {
        "code": "ZOP_OBUKA",
        "name": "Osnovna obuka i provera znanja iz ZOP",
        "subject_kind": ProcessType.SUBJECT_EMPLOYEE,
        "domain": ProcessType.DOMAIN_ZOP,
        "shape": ProcessType.SHAPE_PERIODIC,
        "proof_kind": ProcessType.PROOF_RECORDED,
        "legal_basis": "Zakon o ZOP, čl. 53",
        "default_period_months": 36,
        "period_rules": [],
        "reminder_offsets": [-30, 0, 14],
        "applicability_rule": {"always": True},
        "company_document_kind": "",
        "include_in_medical_exam_record": False,
    },
    {
        "code": "PP_APARATI_SERVIS",
        "name": "Servis PP aparata",
        "subject_kind": ProcessType.SUBJECT_EQUIPMENT,
        "domain": ProcessType.DOMAIN_ZOP,
        "shape": ProcessType.SHAPE_PERIODIC,
        "proof_kind": ProcessType.PROOF_UPLOAD,
        "legal_basis": "Zakon o ZOP, čl. 43-44",
        "default_period_months": 6,
        "period_rules": [],
        "reminder_offsets": [-14, 0, 7],
        "applicability_rule": {"requires_installation": "FIRE_EXTINGUISHERS"},
        "company_document_kind": "",
        "include_in_medical_exam_record": False,
    },
    {
        "code": "HIDRANTI_ISPITIVANJE",
        "name": "Ispitivanje hidrantske mreže",
        "subject_kind": ProcessType.SUBJECT_CLIENT_COMPANY,
        "domain": ProcessType.DOMAIN_ZOP,
        "shape": ProcessType.SHAPE_PERIODIC,
        "proof_kind": ProcessType.PROOF_UPLOAD,
        "legal_basis": "",
        "default_period_months": 6,
        "period_rules": [],
        "reminder_offsets": [-14, 0, 7],
        "applicability_rule": {"requires_installation": "HYDRANT_NETWORK"},
        "company_document_kind": "",
        "include_in_medical_exam_record": False,
    },
    {
        "code": "HIDRANTSKA_CREVA",
        "name": "Ispitivanje creva hidrantske mreže",
        "subject_kind": ProcessType.SUBJECT_CLIENT_COMPANY,
        "domain": ProcessType.DOMAIN_ZOP,
        "shape": ProcessType.SHAPE_PERIODIC,
        "proof_kind": ProcessType.PROOF_UPLOAD,
        "legal_basis": "",
        "default_period_months": 12,
        "period_rules": [],
        "reminder_offsets": [-14, 0, 7],
        "applicability_rule": {"requires_installation": "HYDRANT_NETWORK"},
        "company_document_kind": "",
        "include_in_medical_exam_record": False,
    },
    {
        "code": "SDP_PREGLED",
        "name": "Stručni pregled stabilne instalacije za dojavu požara",
        "subject_kind": ProcessType.SUBJECT_CLIENT_COMPANY,
        "domain": ProcessType.DOMAIN_ZOP,
        "shape": ProcessType.SHAPE_PERIODIC,
        "proof_kind": ProcessType.PROOF_UPLOAD,
        "legal_basis": "",
        "default_period_months": 12,
        "period_rules": [],
        "reminder_offsets": [-30, 0, 14],
        "applicability_rule": {"requires_installation": "FIRE_ALARM_SYSTEM"},
        "company_document_kind": "",
        "include_in_medical_exam_record": False,
    },
    {
        "code": "PLAN_ZOP",
        "name": "Plan zaštite od požara",
        "subject_kind": ProcessType.SUBJECT_CLIENT_COMPANY,
        "domain": ProcessType.DOMAIN_ZOP,
        "shape": ProcessType.SHAPE_LIVING_DOCUMENT,
        "proof_kind": ProcessType.PROOF_UPLOAD,
        "legal_basis": "Zakon o ZOP, čl. 27",
        "default_period_months": None,
        "period_rules": [],
        "reminder_offsets": [],
        "applicability_rule": {"zop_category_in": ["I", "II"]},
        "company_document_kind": "",
        "include_in_medical_exam_record": False,
    },
    {
        "code": "PRAVILA_ZOP",
        "name": "Pravila zaštite od požara",
        "subject_kind": ProcessType.SUBJECT_CLIENT_COMPANY,
        "domain": ProcessType.DOMAIN_ZOP,
        "shape": ProcessType.SHAPE_LIVING_DOCUMENT,
        "proof_kind": ProcessType.PROOF_UPLOAD,
        "legal_basis": "Zakon o ZOP, čl. 28",
        "default_period_months": None,
        "period_rules": [],
        "reminder_offsets": [],
        "applicability_rule": {"zop_category_in": ["III"]},
        "company_document_kind": "",
        "include_in_medical_exam_record": False,
    },
    {
        "code": "PLAN_EVAKUACIJE",
        "name": "Plan evakuacije",
        "subject_kind": ProcessType.SUBJECT_CLIENT_COMPANY,
        "domain": ProcessType.DOMAIN_ZOP,
        "shape": ProcessType.SHAPE_LIVING_DOCUMENT,
        "proof_kind": ProcessType.PROOF_UPLOAD,
        "legal_basis": "Zakon o ZOP, čl. 27a",
        "default_period_months": None,
        "period_rules": [],
        "reminder_offsets": [],
        "applicability_rule": {"always": True},
        "company_document_kind": "",
        "include_in_medical_exam_record": False,
    },
    {
        "code": "LICE_ZOP",
        "name": "Imenovanje lica za ZOP",
        "subject_kind": ProcessType.SUBJECT_CLIENT_COMPANY,
        "domain": ProcessType.DOMAIN_ZOP,
        "shape": ProcessType.SHAPE_APPOINTMENT,
        "proof_kind": ProcessType.PROOF_UPLOAD,
        "legal_basis": "Zakon o ZOP, čl. 52",
        "default_period_months": None,
        "period_rules": [],
        "reminder_offsets": [],
        "applicability_rule": {"always": True},
        "company_document_kind": "DECISION_ZOP",
        "include_in_medical_exam_record": False,
    },
    {
        "code": "PRETHODNI_LEKARSKI",
        "name": "Prethodni lekarski pregled",
        "subject_kind": ProcessType.SUBJECT_EMPLOYEE,
        "domain": ProcessType.DOMAIN_BZNR,
        "shape": ProcessType.SHAPE_PERIODIC,
        "proof_kind": ProcessType.PROOF_UPLOAD,
        "legal_basis": "Zakon o BZR 35/2023, čl. 56",
        "default_period_months": None,
        "period_rules": [],
        "reminder_offsets": [-7, 0, 7],
        "applicability_rule": {"high_risk_only": True},
        "company_document_kind": "",
        "include_in_medical_exam_record": True,
    },
]

BACKFILL_DOCUMENT_KINDS = {
    "PLAN_ZOP": "PLAN_ZOP",
    "PRAVILA_ZOP": "PRAVILA_ZOP",
    "PLAN_EVAKUACIJE": "PLAN_EVAKUACIJE",
    "LICE_ZOP": "DECISION_ZOP",
}


class Command(BaseCommand):
    help = "Seed the obligation catalog ProcessTypes."

    @transaction.atomic
    def handle(self, *args, **options):
        created = 0
        skipped = 0
        for entry in CATALOG:
            code = entry["code"]
            defaults = {k: v for k, v in entry.items() if k != "code"}
            defaults["is_active"] = True
            _, was_created = ProcessType.objects.get_or_create(
                code=code,
                defaults=defaults,
            )
            if was_created:
                created += 1
            else:
                skipped += 1

        backfilled = 0
        for code, kind in BACKFILL_DOCUMENT_KINDS.items():
            updated = ProcessType.objects.filter(
                code=code,
                company_document_kind="",
            ).update(company_document_kind=kind)
            backfilled += updated

        self.stdout.write(
            self.style.SUCCESS(
                f"Obligation catalog: {created} created, {skipped} existing left untouched, "
                f"{backfilled} rows backfilled with company_document_kind.",
            ),
        )
