import type { TestFlowPhase, TestFlowSectionMeta } from "./types";

export const TEST_FLOW_PHASES: TestFlowPhase[] = [
    {
        id: "01_wizard",
        title: "01 — Čarobnjak (nova firma)",
        description: "Šta je app → pet koraka → Plan obaveza",
    },
    {
        id: "02_pregled",
        title: "02 — Tab Plan obaveza",
        description: "Katalog statusa — šta važi za firmu",
    },
    {
        id: "03_licna_karta",
        title: "03 — Tab Lična karta",
        description: "Podaci, profil, kontakt, upitnik",
    },
    {
        id: "04_dokumentacija",
        title: "04 — Tab Dokumentacija",
        description: "Akt, obavezna, nacrti, nalazi, generisani",
    },
    {
        id: "05_radna_mesta",
        title: "05 — Tab Radna mesta i rizik",
        description: "Mesta, procena, LZO, vrste obuka",
    },
    {
        id: "06_zaposleni",
        title: "06 — Tab Zaposleni",
        description: "Zaposleni, kartica, oprema, povrede",
    },
    {
        id: "07_obaveze",
        title: "07 — Tab Aktivne obaveze",
        description: "Konkretni rokovi → generatori na Planu",
    },
    {
        id: "08_danas_slanja",
        title: "08 — Danas i Slanja",
        description: "Dnevni rad van firme",
    },
    {
        id: "09_korisnici",
        title: "09 — Korisnici i uloge",
        description: "Ko sme šta",
    },
];

export const TEST_FLOW_SECTIONS: TestFlowSectionMeta[] = [
    {
        id: "C00_INTRO",
        kind: "check",
        phaseId: "01_wizard",
        uiGroup: "Pre svega — šta je ovo",
        badge: "Uvod",
        label: "Šta je ova aplikacija",
        hint: "Reci ovo pa tek onda klik",
        say: "Ovo je alat za MAK Total Safety: vodite BZR i ZOP obaveze za klijentske firme — rokovi, dokumenti, podsetnici. Vi ste operativa; firma je klijent. Katalog obaveza (vrste, šabloni) je već ubačen u Administraciji — to ne podešavate svaki dan. Ono što sledi je dnevni rad: nova firma, pa tab po tab. Popuni na listi je samo da ubrzamo demo; u životu se kuca.",
    },
    {
        id: "A1",
        kind: "fill",
        phaseId: "01_wizard",
        uiGroup: "Korak 1 — Lična karta",
        label: "Lična karta + profil firme",
        hint: "Firme → Dodaj firmu → Popuni",
        say: "Prvo nova firma — klijent sa kojim radite. Naziv, PIB, matični; kasnije uvoz iz APR-a kad bude spreman. Odmah i profil: ZOP kategorija, prekidač „delatnost visokog rizika“, čekeri instalacija (hidranti, PP aparati…). To nije dekoracija — od toga Plan obaveza zna šta za ovu firmu važi, a šta je sivo „nije primenljivo“. Dva rizika ne mešati: ovde je rizik DELATNOSTI firme; rizik RADNOG MESTA biraš kasnije na mestu (viljuškarista vs admin).",
        route: "/client-companies/new",
        routeLabel: "Čarobnjak",
    },
    {
        id: "C01_WIZARD_DOCS",
        kind: "check",
        phaseId: "01_wizard",
        uiGroup: "Korak 2 — Obavezna dokumentacija",
        label: "Preskoči dokumentaciju",
        hint: "Samo Sledeći",
        say: "Ovde bi išli papiri koje firma mora da poseduje — ugovor, odluka o imenovanju, pravilnik… To nisu iste stvari kao obaveze sa rokom. Obaveza = radnja koja se ponavlja (lekarski, servis). Dokument = fajl koji držiš. Preskačem sad; radimo na tabu Dokumentacija.",
    },
    {
        id: "A3",
        kind: "fill",
        phaseId: "01_wizard",
        uiGroup: "Korak 3 — Radna mesta i rizik",
        label: "Prvo radno mesto",
        hint: "Dodaj radno mesto → Popuni",
        say: "Radno mesto: naziv + nivo rizika mesta (vaša skala: nizak / umeren / povećan…). Od rizika MESTA zavisi šta se zaposlenom automatski otvara — npr. povećan → prethodni lekarski; nizak → obuke bez lekarskog. To je drugi rizik, ne onaj prekidač na firmi.",
        route: "/client-companies/new",
        routeLabel: "Čarobnjak",
    },
    {
        id: "F1",
        kind: "fill",
        phaseId: "01_wizard",
        uiGroup: "Korak 4 — Zaposleni",
        label: "Prvi zaposleni",
        hint: "Dodaj → Popuni → Sačuvaj",
        say: "Zaposleni vezan za to mesto. Podaci, sačuvaj — sistem mu sam otvara obaveze po riziku mesta. Ne kucaš katalog ručno po radniku.",
        route: "/client-companies/new",
        routeLabel: "Čarobnjak",
    },
    {
        id: "J1",
        kind: "fill",
        phaseId: "01_wizard",
        uiGroup: "Korak 5 — Obaveze",
        label: "Prva obaveza (opciono)",
        hint: "Dodaj obavezu → Popuni",
        say: "Ako već imate zakazan npr. periodični lekarski — dodate ovde. Inače prazno: većina obaveza se otvara sama kad zaposlite / dodate opremu. Ovo je ručni dodatak.",
        route: "/client-companies/new",
        routeLabel: "Čarobnjak",
    },
    {
        id: "C01_FINISH",
        kind: "check",
        phaseId: "01_wizard",
        uiGroup: "Kraj čarobnjaka",
        label: "Završi → Plan obaveza",
        hint: "Prvi tab firme",
        say: "Završi otvara firmu na tabu Plan obaveza. Odavde idemo tabovima redom. Ako ste u koraku 1 čekirali profil, lista već ima smisla — sivo samo što stvarno ne važi.",
    },

    {
        id: "C02_OVERVIEW_LIST",
        kind: "check",
        phaseId: "02_pregled",
        uiGroup: "Tab Plan obaveza",
        label: "Šta je Plan obaveza",
        hint: "Katalog + status — pročitaj pa reci",
        say: "Plan obaveza — checklista šta firma po katalogu treba da pokrije. Dve grupe: BZR (bezbednost i zdravlje na radu) i ZOP (zaštita od požara). Lista je ISTI katalog za sve firme; razlika je status. Sivo „nije primenljivo“ = za OVU firmu još ne važi po profilu (visok rizik delatnosti → lekarski; instalacije → hidrant/PP/dojava). Boja (nedostaje / kasni / uskoro / u redu) = važi, to je posao. Pravni osnov = član zakona. Ovo NIJE lista rokova po Petru — to je tab Aktivne obaveze. Ovde: da li tip obaveze uopšte važi i kako stoji u celini.",
    },
    {
        id: "C02_OVERVIEW_MENU",
        kind: "check",
        phaseId: "02_pregled",
        uiGroup: "Tab Plan obaveza",
        label: "Meni reda (⋮ Ispravi)",
        hint: "Vodi tamo gde se rešava",
        say: "Na redu u boji — ⋮ Ispravi vodi na tab gde se to rešava. Sivo po profilu nema Ispravi; pali se kad na Ličnoj karti / profilu čekiraš što treba.",
    },
    {
        id: "C02_NAP",
        kind: "check",
        phaseId: "02_pregled",
        uiGroup: "Tab Plan obaveza",
        label: "Dve vrste „nije primenljivo“",
        hint: "Automatski sivo vs ručno + razlog",
        say: "Dve priče. Jedna: automatski sivo — profil ne pokriva (nema hidranta → hidrant sivo). Druga: vi ručno ⋮ Nije primenljivo + razlog — izuzetak za ovu firmu, da se vidi zašto. Vrati postoji. Obaveze koje su u katalogu „uvek“ (npr. LZO, osnovne obuke) neće biti sive zbog profila — ako fale, biće nedostaje.",
    },
    {
        id: "C02_OVERVIEW_BTNS",
        kind: "check",
        phaseId: "02_pregled",
        uiGroup: "Tab Plan obaveza — dugmad gore",
        label: "Tri generatora (nisu checklista)",
        hint: "Obrazac 1, Registar, Akt",
        say: "Gore desno: Generiši Obrazac 1, Registar mesta sa povećanim rizikom, Generiši Akt. To su izlazni dokumenti kad imaš podatke — nisu statusi u listi. Sad samo pokažem; kliknem kad završimo lekarske / imamo šta da uđe.",
    },

    {
        id: "C03_HEADER",
        kind: "check",
        phaseId: "03_licna_karta",
        uiGroup: "Tab Lična karta — zaglavlje",
        label: "Zaglavlje i bedževi",
        hint: "Šta firma „jeste“ na prvi pogled",
        say: "Lična karta — ko je klijent. Bedževi: ZOP kategorija, visok rizik delatnosti, koje instalacije, test režim mejlova. To je isti profil što vuče Plan obaveza.",
    },
    {
        id: "C03_EDIT_BASIC",
        kind: "check",
        phaseId: "03_licna_karta",
        uiGroup: "Tab Lična karta — Izmeni podatke",
        label: "Osnovni podaci + kontakt",
        hint: "Kartoteka klijenta",
        say: "Izmeni podatke — naziv, PIB, matični, adresa, telefon, email, napomene. Obična kartoteka.",
    },
    {
        id: "P_PROFIL",
        kind: "fill",
        phaseId: "03_licna_karta",
        uiGroup: "Tab Lična karta — Izmeni podatke",
        badge: "Profil",
        label: "Profil (provera / izmena)",
        hint: "Već u čarobnjaku; ovde se menja",
        say: "Profil: ZOP, delatnost visokog rizika, instalacije. U čarobnjaku smo to već rekli; ovde se menja tokom života firme. Čim sačuvaš — Plan obaveza se ponaša drugačije (sivo ↔ boja).",
    },
    {
        id: "C03_EMAIL_MODE",
        kind: "check",
        phaseId: "03_licna_karta",
        uiGroup: "Tab Lična karta — Izmeni podatke",
        label: "Test režim mejlova",
        hint: "Ne spamuj klijenta dok vežbaš",
        say: "Test režim: mailovi ne idu klijentu nego na naše test adrese. Uključeno dok podešavate / snimate; za pravog klijenta u produkciji — isključeno.",
    },
    {
        id: "B",
        kind: "fill",
        phaseId: "03_licna_karta",
        uiGroup: "Tab Lična karta — Kontakt-lica",
        label: "Kontakt-lice",
        hint: "Kome u firmi idu mejlovi poslodavcu",
        say: "Kontakt-lice — osoba kod klijenta (direktor, referent…). Na tu adresu idu mejlovi poslodavcu (uput, potvrde…). Dodaj, sačuvaj, može izmena.",
    },
    {
        id: "C03_INTAKE",
        kind: "check",
        phaseId: "03_licna_karta",
        uiGroup: "Tab Lična karta — Upitnik klijentu",
        label: "Upitnik + prijave",
        hint: "Klijent sam prijavi → vi odobrite",
        say: "Upitnik: pošaljete link, klijent prijavi novog zaposlenog ili opremu bez da vas zove. Prijava stigne ovde — Odobri / Odbij. Manje kucanja za vas.",
    },

    {
        id: "C04_INSPECTION",
        kind: "check",
        phaseId: "04_dokumentacija",
        uiGroup: "Tab Dokumentacija — vrh",
        label: "Za inspekciju (PDF)",
        hint: "Jedan paket za nositi",
        say: "Dokumentacija = papiri firme, odvojeno od Plan obaveza (rokovi). Za inspekciju — jedan PDF paket od onoga što je priloženo. Kad traže „donesi dokumentaciju“.",
    },
    {
        id: "D_DATE",
        kind: "fill",
        phaseId: "04_dokumentacija",
        uiGroup: "Tab Dokumentacija — Akt o proceni rizika",
        label: "Datum akta + sekcije",
        hint: "Akt nije ista stvar kao Plan obaveza",
        say: "Akt o proceni rizika — živi dokument: datum donošenja, sekcije uvod / procene po mestu / zaključak. Papir koji firma drži; menja se tokom vremena.",
    },
    {
        id: "D_REASON",
        kind: "fill",
        phaseId: "04_dokumentacija",
        uiGroup: "Tab Dokumentacija — Akt o proceni rizika",
        label: "Razlog izmene sekcije",
        hint: "Obavezno pri izmeni",
        say: "Menjaš postojeću sekciju — mora razlog. Bez toga ne pušta. Trag zašto je dirano.",
    },
    {
        id: "C04_ACT_MERGE",
        kind: "check",
        phaseId: "04_dokumentacija",
        uiGroup: "Tab Dokumentacija — Akt o proceni rizika",
        label: "Objedini u PDF",
        hint: "Sekcije → jedan fajl",
        say: "Kad su sekcije unutra — Objedini u PDF, jedan spojen dokument za arhivu ili slanje.",
    },
    {
        id: "D_AMD",
        kind: "fill",
        phaseId: "04_dokumentacija",
        uiGroup: "Tab Dokumentacija — Akt o proceni rizika",
        label: "Izmena i dopuna Akta",
        hint: "Nova verzija, stari ostaje",
        say: "Kad se firma promeni (novo mesto, oprema) — ne brišeš stari akt. Dodaješ izmenu i dopunu: naslov, napomena, fajl. Istorija ostaje.",
    },
    {
        id: "C04_BZR_DRAFTS",
        kind: "check",
        phaseId: "04_dokumentacija",
        uiGroup: "Tab Dokumentacija — BZR dokumenti",
        label: "BZR nacrti",
        hint: "Skini, proveri, javi ako ne valja",
        say: "Nacrti BZR dokumenata (programi, pravilnici…) — skinete, vidite da li sede. Ako nešto treba drugačije, čujemo se.",
    },
    {
        id: "C04_WORD_PDF",
        kind: "check",
        phaseId: "04_dokumentacija",
        uiGroup: "Tab Dokumentacija — Obavezna dokumentacija",
        label: "Obavezna dokumentacija",
        hint: "Word → PDF; brojač X/N",
        say: "Obavezna dokumentacija — pravilnik, rešenja… Word se sam pretvara u PDF. Brojač kaže koliko fali do kompleta.",
    },
    {
        id: "L_DATE",
        kind: "fill",
        phaseId: "04_dokumentacija",
        uiGroup: "Tab Dokumentacija — Stručni nalazi",
        label: "Stručni nalaz",
        hint: "Ispitivanja sa rokom",
        say: "Stručni nalazi — ispitivanja (oprema, elektro, mikroklima…). Datum + fajl; rok i status računa sistem. Šta je relevantno zavisi i od instalacija na profilu.",
    },
    {
        id: "C04_GENERATED",
        kind: "check",
        phaseId: "04_dokumentacija",
        uiGroup: "Tab Dokumentacija — Generisani dokumenti",
        label: "Generisani dokumenti",
        hint: "Obrazac 6, revers, potvrde",
        say: "Sve što ste generisali za zaposlene (Obrazac 6, revers LZO, potvrde) — ovde za celu firmu. I dugme Obrazac 6 za sve odjednom.",
    },

    {
        id: "E_ADD",
        kind: "fill",
        phaseId: "05_radna_mesta",
        uiGroup: "Tab Radna mesta — lista",
        label: "Dodaj radno mesto",
        hint: "Naziv + rizik mesta",
        say: "Radna mesta: naziv i nivo rizika mesta. Tu kasnije sedi procena i LZO — jednom za mesto, za sve na njemu.",
    },
    {
        id: "E_EDIT",
        kind: "fill",
        phaseId: "05_radna_mesta",
        uiGroup: "Tab Radna mesta — lista",
        label: "Izmeni radno mesto",
        hint: "Rizik ostaje obavezan",
        say: "Izmena mesta — rizik i dalje obavezan. To vuče šta zaposleni dobija i šta ulazi u papire.",
    },
    {
        id: "C05_RISK_TEXT",
        kind: "check",
        phaseId: "05_radna_mesta",
        uiGroup: "Tab Radna mesta — Procena rizika",
        label: "Procena rizika (tekst)",
        hint: "Opasnosti i mere po mestu",
        say: "Procena rizika po mestu — opasnosti i mere. Jednom napisano; ide u Obrazac 6 za svakog na tom mestu.",
    },
    {
        id: "C05_LZO",
        kind: "check",
        phaseId: "05_radna_mesta",
        uiGroup: "Tab Radna mesta — LZO",
        label: "LZO po mestu",
        hint: "Lična zaštitna oprema",
        say: "LZO — lična zaštitna oprema (šlem, cipele…). Po mestu; ide u Revers LZO. Ne otpremaš blanko šablon po svakom mestu.",
    },
    {
        id: "C05_TRAINING_TYPE",
        kind: "check",
        phaseId: "05_radna_mesta",
        uiGroup: "Tab Radna mesta — Vrste obuka",
        label: "Vrsta obuke + blanko",
        hint: "Preduslov za potvrdu čl. 5",
        say: "Vrste obuka odvojeno od mesta — ista obuka može za više mesta. Blanko potvrdu (čl. 5) otpremiš jednom na vrsti. Bez toga dugme Potvrda na zaposlenom ne radi.",
    },

    {
        id: "F2",
        kind: "fill",
        phaseId: "06_zaposleni",
        uiGroup: "Tab Zaposleni — lista",
        label: "Zaposleni na povećanom riziku mesta",
        hint: "Viljuškarista",
        say: "Zaposleni na mestu sa povećanim rizikom — sam dobija obuke, ZOP, LZO i prethodni lekarski. Periodični lekarski se još ne otvara; pravi se kad završiš prethodni (lančanje).",
    },
    {
        id: "F3",
        kind: "fill",
        phaseId: "06_zaposleni",
        uiGroup: "Tab Zaposleni — lista",
        label: "Zaposleni na umerenom riziku",
        hint: "Magacioner",
        say: "Na umerenom / niskom mestu — obuke i LZO, bez lekarskog. Uporedi dve kartice: razlika je poenta rizika mesta.",
    },
    {
        id: "C06_OPEN_EMP",
        kind: "check",
        phaseId: "06_zaposleni",
        uiGroup: "Kartica zaposlenog",
        label: "Auto-obaveze na kartici",
        hint: "Klik na red",
        say: "Otvoriš zaposlenog — lista obaveza što se sama otvorila pri zaposlenju. To je srž: katalog se ne kuca ručno po radniku.",
    },
    {
        id: "C06_RISK_OVERRIDE",
        kind: "check",
        phaseId: "06_zaposleni",
        uiGroup: "Kartica zaposlenog",
        label: "Rizik — izuzetak (na zaposlenom)",
        hint: "Bez diranja radnog mesta",
        say: "Izuzetak: ovaj radnik na mestu sa visokim rizikom samo prenosi kutije — na njemu staviš niži rizik, mesto ostaje. Obrnuto isto. Ne diraš definiciju mesta.",
    },
    {
        id: "C06_OBRAZAC6",
        kind: "check",
        phaseId: "06_zaposleni",
        uiGroup: "Kartica zaposlenog — dokumenti",
        label: "Obrazac 6",
        hint: "Evidencija o osposobljenosti",
        say: "Obrazac 6 — evidencija o osposobljenosti. Klik: opasnosti/mere i LZO sa mesta + ime radnika, gotov fajl. Ne kucaš papir.",
    },
    {
        id: "C06_REVERS",
        kind: "check",
        phaseId: "06_zaposleni",
        uiGroup: "Kartica zaposlenog — dokumenti",
        label: "Revers LZO",
        hint: "Karton zaduženja",
        say: "Revers LZO — karton zaduženja opreme, iz LZO sa mesta + zaposleni.",
    },
    {
        id: "C06_POTVRDA",
        kind: "check",
        phaseId: "06_zaposleni",
        uiGroup: "Kartica zaposlenog — dokumenti",
        label: "Potvrda (čl. 5)",
        hint: "Treba vrsta obuke + blanko",
        say: "Potvrda po članu 5 — biraš vrstu obuke. Dugme radi tek kad na firmi postoji vrsta sa otpremljenim blankom.",
    },
    {
        id: "C06_TEST",
        kind: "check",
        phaseId: "06_zaposleni",
        uiGroup: "Kartica zaposlenog — test",
        label: "Test obuke",
        hint: "≥75% → obuka + Obrazac 6",
        say: "Test znanja: ≥75% — sama upiše da je obuka gotova i generiše Obrazac 6. Ispod — ponovi. Stvarna provera, ne samo papir.",
    },
    {
        id: "C06_TRAININGS",
        kind: "check",
        phaseId: "06_zaposleni",
        uiGroup: "Kartica zaposlenog — Obuke",
        label: "Evidencija obuka",
        hint: "I ručni unos",
        say: "Kartica Obuke — šta je završeno, do kad važi. Ručno dodaješ obuke van testa (eksterna, stari podaci).",
    },
    {
        id: "C06_EMP_DOCS",
        kind: "check",
        phaseId: "06_zaposleni",
        uiGroup: "Kartica zaposlenog — Dokumenti",
        label: "Dokumenti zaposlenog",
        hint: "Preuzmi",
        say: "Svi generisani dokumenti ovog zaposlenog na jednom mestu — Preuzmi.",
    },
    {
        id: "EQ1",
        kind: "fill",
        phaseId: "06_zaposleni",
        uiGroup: "Tab Zaposleni — Oprema",
        label: "Oprema + servis",
        hint: "Kao zaposleni, nosi rok",
        say: "Ispod je oprema firme. PP aparat + vrsta obaveze servisa — sačuvaš, rok servisa je otvoren, isto kao obaveza na zaposlenom.",
        route: "/equipment",
        routeLabel: "Oprema",
    },
    {
        id: "C06_INJURY",
        kind: "check",
        phaseId: "06_zaposleni",
        uiGroup: "Tab Zaposleni — Povrede",
        label: "Povrede na radu",
        hint: "Evidencija",
        say: "Povrede — evidencija na firmi: ko, kad, težina, opis. Da stoji negde uz zaposlene.",
    },

    {
        id: "C07_LIST",
        kind: "check",
        phaseId: "07_obaveze",
        uiGroup: "Tab Aktivne obaveze",
        label: "Plan vs Aktivne — razlika",
        hint: "Ovo je drugi tab, drugi posao",
        say: "Aktivne obaveze — konkretni rokovi: ko (firma / Petar / PP aparat), koja vrsta, do kad. Plan obaveza = da li tip uopšte važi i status u celini. Aktivne = dnevni rad po slučajevima. Dve reči: tip u katalogu = obaveza; pojava sa rokom = aktivnost (isto što i na meniju Aktivnosti).",
    },
    {
        id: "C07_ADD_BINDING",
        kind: "check",
        phaseId: "07_obaveze",
        uiGroup: "Tab Aktivne obaveze",
        label: "Dodaj obavezu ručno",
        hint: "Van auto-otvaranja",
        say: "Ručno dodavanje kad treba nešto van onoga što se samo otvorilo pri zaposlenju / opremi.",
    },
    {
        id: "C07_FILTERS",
        kind: "check",
        phaseId: "07_obaveze",
        uiGroup: "Aktivnosti (globalni meni ili ovaj tab)",
        label: "Filteri Kasni / Stiže / Otvorene",
        hint: "Nađi prethodni lekarski",
        say: "Filtriraš kasni, stiže uskoro, otvoreno — nađeš prethodni lekarski ili šta god treba da se završi danas.",
        route: "/processes/runs",
        routeLabel: "Aktivnosti",
    },
    {
        id: "K",
        kind: "fill",
        phaseId: "07_obaveze",
        uiGroup: "Aktivnosti — završetak",
        label: "Završi lekarski",
        hint: "Nalaz + važi do",
        say: "Završi aktivnost — datum, broj izveštaja, ocena sposobnosti, mere, PDF nalaza, do kad važi. To zatvara ovaj ciklus.",
        route: "/processes/runs",
        routeLabel: "Aktivnosti",
    },
    {
        id: "C07_CHAIN",
        kind: "check",
        phaseId: "07_obaveze",
        uiGroup: "Aktivnosti — lančanje",
        label: "Lančanje → periodični",
        hint: "Zašto se ne otvara pri zaposlenju",
        say: "Posle završetka prethodnog — sam se pojavi periodični sa novim rokom. Ne pri zaposlenju, jer rok zavisi od nalaza lekara. Zato „lančanje“.",
    },
    {
        id: "C07_OBRAZAC1",
        kind: "check",
        phaseId: "07_obaveze",
        uiGroup: "Nazad na Plan obaveza",
        label: "Generiši Obrazac 1",
        hint: "Sad ima završenih pregleda",
        say: "Nazad na Plan obaveza → Generiši Obrazac 1. Evidencija lekarskih iz završenih aktivnosti — tabela, ne kucaš. Ide i u Dokumentaciju.",
    },
    {
        id: "C07_REGISTAR",
        kind: "check",
        phaseId: "07_obaveze",
        uiGroup: "Nazad na Plan obaveza",
        label: "Registar ↑ rizik",
        hint: "Drugo dugme",
        say: "Registar radnih mesta sa povećanim rizikom — isto princip, drugi papir.",
    },
    {
        id: "C07_ACT_GEN",
        kind: "check",
        phaseId: "07_obaveze",
        uiGroup: "Nazad na Plan obaveza",
        label: "Generiši Akt",
        hint: "Treće dugme",
        say: "Generiši Akt — kad su podaci spremni. Alternativa / dopuna ručnom aktu na Dokumentaciji.",
    },

    {
        id: "C08_DANAS",
        kind: "check",
        phaseId: "08_danas_slanja",
        uiGroup: "Danas",
        label: "Semafor Danas",
        hint: "Zašto app postoji",
        say: "Danas — van firme, dnevni semafor: šta kasni, šta stiže uskoro, neuspela slanja. Suština proizvoda: ne vodiš rokove u glavi.",
        route: "/danas",
        routeLabel: "Danas",
    },
    {
        id: "C08_SLANJA",
        kind: "check",
        phaseId: "08_danas_slanja",
        uiGroup: "Slanja",
        label: "Ko je primalac",
        hint: "Istorija mejlova",
        say: "Slanja — istorija. Bitno ko dobija šta: podsetnik lekarskog unapred nama (MAK), uput na dan firmi, kad kasni opet nama. Pregled mejla, Ponovi ako padne.",
        route: "/processes/outbox",
        routeLabel: "Slanja",
    },

    {
        id: "C09_USER",
        kind: "check",
        phaseId: "09_korisnici",
        uiGroup: "Korisnici",
        label: "Korisnik + uloga",
        hint: "Email obavezan",
        say: "Operativa = dnevni rad na firmama. Pregled (uloga) = korisnici/uloge. Admin = setup kataloga. Email mora — interni podsetnici idu na te adrese.",
        route: "/users",
        routeLabel: "Korisnici",
    },
    {
        id: "C09_ROLE",
        kind: "check",
        phaseId: "09_korisnici",
        uiGroup: "Uloge",
        label: "Uloga / permisije",
        hint: "Pa se prijavi kao taj",
        say: "Uloga čekira šta sme. Kad se prijavi — dugme bez prava se ne pojavi. Ako treba nova uloga, dodamo i to postane standard.",
        route: "/roles",
        routeLabel: "Uloge",
    },
];
