import type { TestFlowPhase, TestFlowSectionMeta } from "./types";

export const TEST_FLOW_PHASES: TestFlowPhase[] = [
    {
        id: "prep",
        title: "Podešavanja",
        description: "Šabloni i vrste obaveza (pre lekarskih pregleda).",
    },
    {
        id: "wizard",
        title: "Čarobnjak — nova firma",
        description: "",
    },
    {
        id: "wizard_medical",
        title: "Lekarski pregled",
        description: "",
    },
    {
        id: "company",
        title: "Firma — tabovi",
        description: "",
    },
    {
        id: "ops",
        title: "Operativa i pregled",
        description: "",
    },
    {
        id: "optional",
        title: "Opciono",
        description: "",
    },
];

export const TEST_FLOW_SECTIONS: TestFlowSectionMeta[] = [
    {
        id: "G",
        phaseId: "prep",
        label: "G — Šablon dokumenta (Uput)",
        hint: "Dodaj šablon → Popuni → priloži PDF → Sačuvaj",
        route: "/documents/templates",
        routeLabel: "Šabloni dokumenata",
    },
    {
        id: "H",
        phaseId: "prep",
        label: "H — Vrsta obaveze",
        hint: "Dodaj vrstu obaveze → Popuni → Sačuvaj",
        route: "/processes/types",
        routeLabel: "Vrste obaveza",
    },
    {
        id: "I1",
        phaseId: "prep",
        label: "I — Okidač: Na zakazani datum",
        hint: "Red Periodični lekarski pregled → Dodaj okidač → Popuni → Sačuvaj",
        route: "/processes/templates",
        routeLabel: "Šabloni obaveza",
    },
    {
        id: "I2",
        phaseId: "prep",
        label: "I — Okidač: Kada se završi pregled",
        hint: "Isti red → drugi okidač → Popuni → Sačuvaj",
        route: "/processes/templates",
        routeLabel: "Šabloni obaveza",
    },
    {
        id: "A1",
        phaseId: "wizard",
        label: "A1 — Lična karta",
        hint: "Čarobnjak korak 1 → Popuni → Uvezi matični → Sledeći",
        route: "/client-companies/new",
        routeLabel: "Nova firma",
    },
    {
        id: "A3",
        phaseId: "wizard",
        label: "A3 — Radno mesto",
        hint: "Čarobnjak korak 3 → Popuni → Dodaj radno mesto → Sledeći",
        route: "/client-companies/new",
        routeLabel: "Nova firma",
    },
    {
        id: "F1",
        phaseId: "wizard",
        label: "F1 — Zaposleni (Marko)",
        hint: "Čarobnjak korak 4 → Dodaj zaposlenog → Popuni → Sačuvaj",
        route: "/client-companies/new",
        routeLabel: "Nova firma",
    },
    {
        id: "J1",
        phaseId: "wizard_medical",
        label: "J1 — Obaveza za zaposlenog",
        hint: "Čarobnjak korak 5 → Dodaj obavezu kod zaposlenog → Popuni → Dodaj",
        route: "/client-companies/new",
        routeLabel: "Nova firma",
    },
    {
        id: "B",
        phaseId: "company",
        label: "B — Kontakt-lice",
        hint: "Tab Lična karta → Dodaj kontakt-lice → Popuni",
    },
    {
        id: "D_DATE",
        phaseId: "company",
        label: "D — Datum akta",
        hint: "Tab Dokumentacija → Akt o proceni rizika → Dodaj Akt",
    },
    {
        id: "D_REASON",
        phaseId: "company",
        label: "D — Razlog izmene (akt)",
        hint: "Otvoren dialog priloga sekcije akta",
    },
    {
        id: "E_ADD",
        phaseId: "company",
        label: "E — Dodaj radno mesto",
        hint: "Tab Radna mesta → Dodaj radno mesto",
    },
    {
        id: "E_EDIT",
        phaseId: "company",
        label: "E — Izmeni Viljuškarista",
        hint: "Tab Radna mesta → izmena Viljuškarista",
    },
    {
        id: "L_DATE",
        phaseId: "company",
        label: "L — Datum stručnog nalaza",
        hint: "Tab Stručni nalazi → dialog priloga",
    },
    {
        id: "K",
        phaseId: "ops",
        label: "K — Završi aktivnost",
        hint: "Operativa → Aktivnosti → Detalji → Završetak",
        route: "/processes/runs",
        routeLabel: "Aktivnosti",
    },
    {
        id: "O",
        phaseId: "ops",
        label: "O — Predstojeći rokovi",
        hint: "Pregled → Predstojeći rokovi → Popuni filter",
        route: "/processes/upcoming",
        routeLabel: "Predstojeći rokovi",
    },
    {
        id: "M",
        phaseId: "ops",
        label: "M — Nivo rizika TEST",
        hint: "Podešavanja → Nivoi rizika → Dodaj",
        route: "/risk-levels",
        routeLabel: "Nivoi rizika",
    },
    {
        id: "F2",
        phaseId: "optional",
        label: "F2 — Zaposleni (random)",
        hint: "Dialog Dodaj zaposlenog — novi podaci svaki put",
    },
    {
        id: "F3",
        phaseId: "optional",
        label: "F3 — Zaposleni (random)",
        hint: "Dialog Dodaj zaposlenog — novi podaci svaki put",
    },
];
