import type { TestFlowPhase, TestFlowSectionMeta } from "./types";

export const TEST_FLOW_PHASES: TestFlowPhase[] = [
    {
        id: "prep",
        title: "Podešavanja",
        description: "Šabloni i vrste obaveza",
    },
    {
        id: "wizard",
        title: "Čarobnjak",
        description: "Nova firma",
    },
    {
        id: "wizard_medical",
        title: "Lekarski pregled",
        description: "",
    },
    {
        id: "company",
        title: "Firma",
        description: "Tabovi",
    },
    {
        id: "ops",
        title: "Operativa",
        description: "",
    },
    {
        id: "optional",
        title: "Opciono",
        description: "",
    },
];

export const TEST_FLOW_SECTIONS: TestFlowSectionMeta[] = [
    {
        id: "G",
        phaseId: "prep",
        label: "Šablon dokumenta (Uput)",
        hint: "Dodaj šablon, priloži PDF, Sačuvaj",
        route: "/documents/templates",
        routeLabel: "Šabloni",
    },
    {
        id: "H",
        phaseId: "prep",
        label: "Vrsta obaveze",
        hint: "Periodični lekarski pregled",
        route: "/processes/types",
        routeLabel: "Vrste obaveza",
    },
    {
        id: "I1",
        phaseId: "prep",
        label: "Okidač — na zakazani datum",
        hint: "Šabloni obaveza → Dodaj okidač",
        route: "/processes/templates",
        routeLabel: "Šabloni obaveza",
    },
    {
        id: "I2",
        phaseId: "prep",
        label: "Okidač — završetak pregleda",
        hint: "Drugi okidač na istom redu",
        route: "/processes/templates",
        routeLabel: "Šabloni obaveza",
    },
    {
        id: "A1",
        phaseId: "wizard",
        label: "Lična karta",
        hint: "Čarobnjak korak 1",
        route: "/client-companies/new",
        routeLabel: "Čarobnjak",
    },
    {
        id: "A3",
        phaseId: "wizard",
        label: "Radno mesto",
        hint: "Čarobnjak korak 3",
        route: "/client-companies/new",
        routeLabel: "Čarobnjak",
    },
    {
        id: "F1",
        phaseId: "wizard",
        label: "Zaposleni (Marko)",
        hint: "Čarobnjak korak 4, dialog otvoren",
        route: "/client-companies/new",
        routeLabel: "Čarobnjak",
    },
    {
        id: "J1",
        phaseId: "wizard_medical",
        label: "Obaveza za zaposlenog",
        hint: "Čarobnjak korak 5",
        route: "/client-companies/new",
        routeLabel: "Čarobnjak",
    },
    {
        id: "B",
        phaseId: "company",
        label: "Kontakt-lice",
        hint: "Tab Lična karta",
    },
    {
        id: "D_DATE",
        phaseId: "company",
        label: "Datum akta",
        hint: "Akt o proceni rizika",
    },
    {
        id: "D_REASON",
        phaseId: "company",
        label: "Razlog izmene (akt)",
        hint: "Dialog priloga sekcije",
    },
    {
        id: "E_ADD",
        phaseId: "company",
        label: "Dodaj radno mesto",
        hint: "Tab Radna mesta",
    },
    {
        id: "E_EDIT",
        phaseId: "company",
        label: "Izmeni Viljuškarista",
        hint: "Tab Radna mesta",
    },
    {
        id: "L_DATE",
        phaseId: "company",
        label: "Datum stručnog nalaza",
        hint: "Tab Stručni nalazi",
    },
    {
        id: "K",
        phaseId: "ops",
        label: "Završi aktivnost",
        hint: "Detalji aktivnosti",
        route: "/processes/runs",
        routeLabel: "Aktivnosti",
    },
    {
        id: "O",
        phaseId: "ops",
        label: "Predstojeći rokovi",
        hint: "Filter pregleda",
        route: "/processes/upcoming",
        routeLabel: "Rokovi",
    },
    {
        id: "M",
        phaseId: "ops",
        label: "Nivo rizika (test)",
        hint: "Dodaj pa obriši",
        route: "/risk-levels",
        routeLabel: "Nivoi rizika",
    },
    {
        id: "F2",
        phaseId: "optional",
        label: "Zaposleni random",
        hint: "Dialog Dodaj zaposlenog",
    },
    {
        id: "F3",
        phaseId: "optional",
        label: "Zaposleni random",
        hint: "Dialog Dodaj zaposlenog",
    },
];
